version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: videotube-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: videotube
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - videotube-dev-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: videotube-minio-dev
    restart: unless-stopped
    ports:
      - "7000:9000"  # API Port
      - "7001:9001"  # Console Port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_dev_data:/data
    networks:
      - videotube-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Backend API (Development mode with hot reload)
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: videotube-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/videotube
      - CORS_ORIGIN=http://localhost:5173
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=videotube
      - MINIO_USE_SSL=false
      - ACCESS_TOKEN_SECRET=your-super-secret-access-token-key-here
      - ACCESS_TOKEN_EXPIRY=1d
      - REFRESH_TOKEN_SECRET=your-super-secret-refresh-token-key-here
      - REFRESH_TOKEN_EXPIRY=10d
    depends_on:
      - mongodb
      - minio
    networks:
      - videotube-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/public:/app/public

volumes:
  mongodb_dev_data:
    driver: local
  minio_dev_data:
    driver: local

networks:
  videotube-dev-network:
    driver: bridge
