version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-local
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      - MINIO_ROOT_USER=minioadmin      # Your access key
      - MINIO_ROOT_PASSWORD=minioadmin  # Your secret key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
