@VideoTube.Api_HostAddress = http://localhost:5266

### Register a new user
POST {{VideoTube.Api_HostAddress}}/api/v1/users/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="FullName"

Ayaz Patel
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Email"

ayaz@example.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Username"

ayazpatel
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Password"

SecurePass123!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Avatar"; filename="C:/Users/ayazp/OneDrive/Pictures/avatar/images.jpeg"
Content-Type: image/jpeg

< C:/Users/ayazp/OneDrive/Pictures/avatar/images.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# GET {{VideoTube.Api_HostAddress}}/weatherforecast/
# Accept: application/json

###


